// Generated by `npm run cj:import` from cj/selection.json - do not edit by hand.
import type { CjCatalog } from './cj-types.js'

export const cjCatalog: CjCatalog = {
  "generatedAt": null,
  "products": []
}
