// Generated by `npm run cj:import` from cj/selection.json - do not edit by hand.
import type { CjCatalog } from './cj-types.js'

export const cjCatalog: CjCatalog = {
  "generatedAt": "2026-09-30T23:20:25.043Z",
  "products": [
    {
      "pid": "2602061003141607600",
      "sku": "CJYD2756123",
      "slug": "body-voile-harnais",
      "name": "Body Voile Harnais",
      "cjName": "Sexy Lingerie Teddy For Women",
      "description": "Un body en voile transparent souligné de fines bretelles graphiques et d'un col ras-du-cou. Structuré, léger, résolument audacieux.",
      "category": "bodys",
      "price": 39.9,
      "images": [
        "/products/CJYD2756123/4c6c4f5f15.webp",
        "/products/CJYD2756123/0d2e8924af.webp",
        "/products/CJYD2756123/0a5d164cdf.webp",
        "/products/CJYD2756123/884a6e20d3.webp",
        "/products/CJYD2756123/b414c7b516.webp",
        "/products/CJYD2756123/b75543ee7d.webp"
      ],
      "variants": [
        {
          "vid": "2602061003141608000",
          "sku": "CJYD275612301AZ",
          "key": "Black-S",
          "color": "Noir",
          "size": "S",
          "cost": 4.34,
          "image": "/products/CJYD2756123/884a6e20d3.webp"
        },
        {
          "vid": "2602061003141609700",
          "sku": "CJYD275612303CX",
          "key": "Black-M",
          "color": "Noir",
          "size": "M",
          "cost": 4.34,
          "image": "/products/CJYD2756123/884a6e20d3.webp"
        },
        {
          "vid": "2602061003141609400",
          "sku": "CJYD275612302BY",
          "key": "Black-L",
          "color": "Noir",
          "size": "L",
          "cost": 4.34,
          "image": "/products/CJYD2756123/884a6e20d3.webp"
        },
        {
          "vid": "2602061003151600000",
          "sku": "CJYD275612304DW",
          "key": "Red-S",
          "color": "Rouge",
          "size": "S",
          "cost": 4.34,
          "image": "/products/CJYD2756123/0d2e8924af.webp"
        },
        {
          "vid": "2602061003151600600",
          "sku": "CJYD275612306FU",
          "key": "Red-M",
          "color": "Rouge",
          "size": "M",
          "cost": 4.34,
          "image": "/products/CJYD2756123/0d2e8924af.webp"
        },
        {
          "vid": "2602061003151600300",
          "sku": "CJYD275612305EV",
          "key": "Red-L",
          "color": "Rouge",
          "size": "L",
          "cost": 4.34,
          "image": "/products/CJYD2756123/0d2e8924af.webp"
        }
      ],
      "isNew": true
    },
    {
      "pid": "1782602200162766848",
      "sku": "CJLY2017836",
      "slug": "ensemble-lanieres",
      "name": "Ensemble Lanières",
      "cjName": "Sexy Lingerie Can Eat Milk Free Sexy Uniform Sexy Lingerie Sexy Clothes Sexy Sexy Pajamas",
      "description": "Soutien-gorge ouvert à lanières, string et jarretières assortis. Un ensemble graphique pour les soirs où l'on ose tout.",
      "category": "ensembles",
      "price": 34.9,
      "images": [
        "/products/CJLY2017836/e98f545220.webp",
        "/products/CJLY2017836/7b353de204.webp",
        "/products/CJLY2017836/cb502f8058.webp",
        "/products/CJLY2017836/26886a2377.webp",
        "/products/CJLY2017836/611d66389c.webp",
        "/products/CJLY2017836/096d5b1fe6.webp",
        "/products/CJLY2017836/574e582306.webp",
        "/products/CJLY2017836/df22aab8b3.webp"
      ],
      "variants": [
        {
          "vid": "1782602202452856832",
          "sku": "CJLY201783602BY",
          "key": "Black-S",
          "color": "Noir",
          "size": "S",
          "cost": 3.02,
          "image": "/products/CJLY2017836/7b353de204.webp"
        },
        {
          "vid": "1782602202507382784",
          "sku": "CJLY201783603CX",
          "key": "Black-M",
          "color": "Noir",
          "size": "M",
          "cost": 3.02,
          "image": "/products/CJLY2017836/7b353de204.webp"
        },
        {
          "vid": "1782602202561908736",
          "sku": "CJLY201783604DW",
          "key": "Black-L",
          "color": "Noir",
          "size": "L",
          "cost": 3.02,
          "image": "/products/CJLY2017836/7b353de204.webp"
        },
        {
          "vid": "1782602202624823296",
          "sku": "CJLY201783605EV",
          "key": "Black-XL",
          "color": "Noir",
          "size": "XL",
          "cost": 3.02,
          "image": "/products/CJLY2017836/7b353de204.webp"
        },
        {
          "vid": "1782602202683543552",
          "sku": "CJLY201783606FU",
          "key": "Black-XXL",
          "color": "Noir",
          "size": "XXL",
          "cost": 3.02,
          "image": "/products/CJLY2017836/7b353de204.webp"
        },
        {
          "vid": "1782602200238264320",
          "sku": "CJLY201783601AZ",
          "key": "Black-XXXL",
          "color": "Noir",
          "size": "XXXL",
          "cost": 3.02,
          "image": "/products/CJLY2017836/7b353de204.webp"
        },
        {
          "vid": "1782602203774062592",
          "sku": "CJLY201783626ZA",
          "key": "Scarlet-S",
          "color": "Noir et rouge",
          "size": "S",
          "cost": 3.02,
          "image": "/products/CJLY2017836/df22aab8b3.webp"
        },
        {
          "vid": "1782602203828588544",
          "sku": "CJLY201783627AZ",
          "key": "Scarlet-M",
          "color": "Noir et rouge",
          "size": "M",
          "cost": 3.02,
          "image": "/products/CJLY2017836/df22aab8b3.webp"
        },
        {
          "vid": "1782602203883114496",
          "sku": "CJLY201783628BY",
          "key": "Scarlet-L",
          "color": "Noir et rouge",
          "size": "L",
          "cost": 3.02,
          "image": "/products/CJLY2017836/df22aab8b3.webp"
        },
        {
          "vid": "1782602203937640448",
          "sku": "CJLY201783629CX",
          "key": "Scarlet-XL",
          "color": "Noir et rouge",
          "size": "XL",
          "cost": 3.02,
          "image": "/products/CJLY2017836/df22aab8b3.webp"
        },
        {
          "vid": "1782602203992166400",
          "sku": "CJLY201783630DW",
          "key": "Scarlet-XXL",
          "color": "Noir et rouge",
          "size": "XXL",
          "cost": 3.02,
          "image": "/products/CJLY2017836/df22aab8b3.webp"
        },
        {
          "vid": "1782602203723730944",
          "sku": "CJLY201783625YB",
          "key": "Scarlet-XXXL",
          "color": "Noir et rouge",
          "size": "XXXL",
          "cost": 3.02,
          "image": "/products/CJLY2017836/df22aab8b3.webp"
        },
        {
          "vid": "1782602202796789760",
          "sku": "CJLY201783608HS",
          "key": "Red-S",
          "color": "Rouge",
          "size": "S",
          "cost": 3.02,
          "image": "/products/CJLY2017836/096d5b1fe6.webp"
        },
        {
          "vid": "1782602202851315712",
          "sku": "CJLY201783609IR",
          "key": "Red-M",
          "color": "Rouge",
          "size": "M",
          "cost": 3.02,
          "image": "/products/CJLY2017836/096d5b1fe6.webp"
        },
        {
          "vid": "1782602202905841664",
          "sku": "CJLY201783610JQ",
          "key": "Red-L",
          "color": "Rouge",
          "size": "L",
          "cost": 3.02,
          "image": "/products/CJLY2017836/096d5b1fe6.webp"
        },
        {
          "vid": "1782602202964561920",
          "sku": "CJLY201783611KP",
          "key": "Red-XL",
          "color": "Rouge",
          "size": "XL",
          "cost": 3.02,
          "image": "/products/CJLY2017836/096d5b1fe6.webp"
        },
        {
          "vid": "1782602203019087872",
          "sku": "CJLY201783612LO",
          "key": "Red-XXL",
          "color": "Rouge",
          "size": "XXL",
          "cost": 3.02,
          "image": "/products/CJLY2017836/096d5b1fe6.webp"
        },
        {
          "vid": "1782602202738069504",
          "sku": "CJLY201783607GT",
          "key": "Red-XXXL",
          "color": "Rouge",
          "size": "XXXL",
          "cost": 3.02,
          "image": "/products/CJLY2017836/096d5b1fe6.webp"
        },
        {
          "vid": "1782602203128139776",
          "sku": "CJLY201783614NM",
          "key": "Purple-S",
          "color": "Violet",
          "size": "S",
          "cost": 3.02,
          "image": "/products/CJLY2017836/574e582306.webp"
        },
        {
          "vid": "1782602203186860032",
          "sku": "CJLY201783615OL",
          "key": "Purple-M",
          "color": "Violet",
          "size": "M",
          "cost": 3.02,
          "image": "/products/CJLY2017836/574e582306.webp"
        },
        {
          "vid": "1782602203245580288",
          "sku": "CJLY201783616PK",
          "key": "Purple-L",
          "color": "Violet",
          "size": "L",
          "cost": 3.02,
          "image": "/products/CJLY2017836/574e582306.webp"
        },
        {
          "vid": "1782602203295911936",
          "sku": "CJLY201783617QJ",
          "key": "Purple-XL",
          "color": "Violet",
          "size": "XL",
          "cost": 3.02,
          "image": "/products/CJLY2017836/574e582306.webp"
        },
        {
          "vid": "1782602203350437888",
          "sku": "CJLY201783618RI",
          "key": "Purple-XXL",
          "color": "Violet",
          "size": "XXL",
          "cost": 3.02,
          "image": "/products/CJLY2017836/574e582306.webp"
        },
        {
          "vid": "1782602203073613824",
          "sku": "CJLY201783613MN",
          "key": "Purple-XXXL",
          "color": "Violet",
          "size": "XXXL",
          "cost": 2.11,
          "image": "/products/CJLY2017836/574e582306.webp"
        }
      ]
    },
    {
      "pid": "1B05B386-BD2D-4614-BD5A-57FBDCEE13FB",
      "sku": "CJNSSYQQ00199",
      "slug": "nuisette-voile-epaules-nues",
      "name": "Nuisette Voile Épaules Nues",
      "cjName": "Sexy lingerie uniform seduction women's see-through dress white gauze show shoulder lace sexy lingerie",
      "description": "Une nuisette vaporeuse en voile transparent, bordée de dentelle, qui dégage les épaules. Livrée avec son string assorti.",
      "category": "lingerie-de-nuit",
      "price": 34.9,
      "images": [
        "/products/CJNSSYQQ00199/944cdb2261.webp",
        "/products/CJNSSYQQ00199/c4a7296310.webp",
        "/products/CJNSSYQQ00199/a99b5e874a.webp",
        "/products/CJNSSYQQ00199/070a99a995.webp",
        "/products/CJNSSYQQ00199/8d74ff1d3f.webp",
        "/products/CJNSSYQQ00199/8285d61a70.webp"
      ],
      "variants": [
        {
          "vid": "D0D13C36-83EB-4FC8-938B-D38D69ECD371",
          "sku": "CJNSSYQQ00199-White-S",
          "key": "White-S",
          "color": "Blanc",
          "size": "S",
          "cost": 2.16,
          "image": "/products/CJNSSYQQ00199/944cdb2261.webp"
        },
        {
          "vid": "8F95BD7A-D188-4372-AEF4-A937417770A8",
          "sku": "CJNSSYQQ00199-White-M",
          "key": "White-M",
          "color": "Blanc",
          "size": "M",
          "cost": 2.16,
          "image": "/products/CJNSSYQQ00199/944cdb2261.webp"
        },
        {
          "vid": "9AA5B368-64AF-4B18-ACB4-06C172910D3C",
          "sku": "CJNSSYQQ00199-White-L",
          "key": "White-L",
          "color": "Blanc",
          "size": "L",
          "cost": 2.16,
          "image": "/products/CJNSSYQQ00199/944cdb2261.webp"
        },
        {
          "vid": "5049197C-BC65-4728-A9F1-25124672FBB9",
          "sku": "CJNSSYQQ00199-White-XL",
          "key": "White-XL",
          "color": "Blanc",
          "size": "XL",
          "cost": 2.16,
          "image": "/products/CJNSSYQQ00199/944cdb2261.webp"
        },
        {
          "vid": "1D93E3B3-54BC-4059-90ED-A004B771B788",
          "sku": "CJNSSYQQ00199-White-XXL",
          "key": "White-XXL",
          "color": "Blanc",
          "size": "XXL",
          "cost": 2.16,
          "image": "/products/CJNSSYQQ00199/944cdb2261.webp"
        },
        {
          "vid": "045E61B0-F1A1-42DA-880A-4536094D89DB",
          "sku": "CJNSSYQQ00199-Black-S",
          "key": "Black-S",
          "color": "Noir",
          "size": "S",
          "cost": 2.16,
          "image": "/products/CJNSSYQQ00199/8285d61a70.webp"
        },
        {
          "vid": "C945FF14-7117-40C0-8E19-9803DCFE3981",
          "sku": "CJNSSYQQ00199-Black-M",
          "key": "Black-M",
          "color": "Noir",
          "size": "M",
          "cost": 2.16,
          "image": "/products/CJNSSYQQ00199/8285d61a70.webp"
        },
        {
          "vid": "BD0F9589-2ADD-49C1-AB65-95F384BCB034",
          "sku": "CJNSSYQQ00199-Black-L",
          "key": "Black-L",
          "color": "Noir",
          "size": "L",
          "cost": 2.16,
          "image": "/products/CJNSSYQQ00199/8285d61a70.webp"
        },
        {
          "vid": "663E7ACE-26A2-4672-B8A8-A151B610FA6F",
          "sku": "CJNSSYQQ00199-Black-XL",
          "key": "Black-XL",
          "color": "Noir",
          "size": "XL",
          "cost": 2.16,
          "image": "/products/CJNSSYQQ00199/8285d61a70.webp"
        },
        {
          "vid": "D194FE35-0A46-4EF9-998B-D102489BD24E",
          "sku": "CJNSSYQQ00199-Black-XXL",
          "key": "Black-XXL",
          "color": "Noir",
          "size": "XXL",
          "cost": 2.16,
          "image": "/products/CJNSSYQQ00199/8285d61a70.webp"
        }
      ],
      "isBestSeller": true
    },
    {
      "pid": "2608230407371636200",
      "sku": "CJYD3087005",
      "slug": "guepiere-dentelle-lacee",
      "name": "Guêpière Dentelle Lacée",
      "cjName": "Sensual And Alluring Lace Sheer Lingerie",
      "description": "Guêpière en dentelle lacée sur le devant, jupette volantée et jarretelles. Disponible avec ou sans bas assortis.",
      "category": "ensembles",
      "price": 44.9,
      "images": [
        "/products/CJYD3087005/db5ae523ef.webp",
        "/products/CJYD3087005/e7061a801e.webp",
        "/products/CJYD3087005/da136156c0.webp",
        "/products/CJYD3087005/8c8f8995d9.webp"
      ],
      "variants": [
        {
          "vid": "2608230407371637200",
          "sku": "CJYD308700501AZ",
          "key": "White-S",
          "color": "Blanc",
          "size": "S",
          "cost": 3.86,
          "image": "/products/CJYD3087005/8c8f8995d9.webp"
        },
        {
          "vid": "2608230407371637201",
          "sku": "CJYD308700502BY",
          "key": "White-M",
          "color": "Blanc",
          "size": "M",
          "cost": 3.86,
          "image": "/products/CJYD3087005/8c8f8995d9.webp"
        },
        {
          "vid": "2608230407371637202",
          "sku": "CJYD308700503CX",
          "key": "White-L",
          "color": "Blanc",
          "size": "L",
          "cost": 3.86,
          "image": "/products/CJYD3087005/8c8f8995d9.webp"
        },
        {
          "vid": "2608230407371637203",
          "sku": "CJYD308700504DW",
          "key": "White-XL",
          "color": "Blanc",
          "size": "XL",
          "cost": 3.86,
          "image": "/products/CJYD3087005/8c8f8995d9.webp"
        },
        {
          "vid": "2608230407371637208",
          "sku": "CJYD308700509IR",
          "key": "White with Stockings-S",
          "color": "Blanc avec bas",
          "size": "S",
          "cost": 4.54,
          "image": "/products/CJYD3087005/e7061a801e.webp"
        },
        {
          "vid": "2608230407371637209",
          "sku": "CJYD308700510JQ",
          "key": "White with Stockings-M",
          "color": "Blanc avec bas",
          "size": "M",
          "cost": 4.54,
          "image": "/products/CJYD3087005/e7061a801e.webp"
        },
        {
          "vid": "2608230407371637210",
          "sku": "CJYD308700511KP",
          "key": "White with Stockings-L",
          "color": "Blanc avec bas",
          "size": "L",
          "cost": 4.54,
          "image": "/products/CJYD3087005/e7061a801e.webp"
        },
        {
          "vid": "2608230407371637211",
          "sku": "CJYD308700512LO",
          "key": "White with Stockings-XL",
          "color": "Blanc avec bas",
          "size": "XL",
          "cost": 4.54,
          "image": "/products/CJYD3087005/e7061a801e.webp"
        },
        {
          "vid": "2608230407371637204",
          "sku": "CJYD308700505EV",
          "key": "Red-S",
          "color": "Rouge",
          "size": "S",
          "cost": 3.86,
          "image": "/products/CJYD3087005/db5ae523ef.webp"
        },
        {
          "vid": "2608230407371637205",
          "sku": "CJYD308700506FU",
          "key": "Red-M",
          "color": "Rouge",
          "size": "M",
          "cost": 3.86,
          "image": "/products/CJYD3087005/db5ae523ef.webp"
        },
        {
          "vid": "2608230407371637206",
          "sku": "CJYD308700507GT",
          "key": "Red-L",
          "color": "Rouge",
          "size": "L",
          "cost": 3.86,
          "image": "/products/CJYD3087005/db5ae523ef.webp"
        },
        {
          "vid": "2608230407371637207",
          "sku": "CJYD308700508HS",
          "key": "Red-XL",
          "color": "Rouge",
          "size": "XL",
          "cost": 3.86,
          "image": "/products/CJYD3087005/db5ae523ef.webp"
        },
        {
          "vid": "2608230407371637212",
          "sku": "CJYD308700513MN",
          "key": "Red  with Stockings-S",
          "color": "Rouge avec bas",
          "size": "S",
          "cost": 4.54,
          "image": "/products/CJYD3087005/da136156c0.webp"
        },
        {
          "vid": "2608230407371637213",
          "sku": "CJYD308700514NM",
          "key": "Red  with Stockings-M",
          "color": "Rouge avec bas",
          "size": "M",
          "cost": 4.54,
          "image": "/products/CJYD3087005/da136156c0.webp"
        },
        {
          "vid": "2608230407371637214",
          "sku": "CJYD308700515OL",
          "key": "Red  with Stockings-L",
          "color": "Rouge avec bas",
          "size": "L",
          "cost": 4.54,
          "image": "/products/CJYD3087005/da136156c0.webp"
        },
        {
          "vid": "2608230407371637215",
          "sku": "CJYD308700516PK",
          "key": "Red  with Stockings-XL",
          "color": "Rouge avec bas",
          "size": "XL",
          "cost": 4.54,
          "image": "/products/CJYD3087005/da136156c0.webp"
        }
      ],
      "isNew": true
    },
    {
      "pid": "2509050112021608000",
      "sku": "CJYD2478752",
      "slug": "nuisette-dos-nu-dentelle",
      "name": "Nuisette Dos Nu Dentelle",
      "cjName": "Sexy Lingerie Women's Halter Nightdress",
      "description": "Nuisette à col licou, bonnets en dentelle et voile fluide jusqu'à mi-cuisse. Le dos nu fait le reste.",
      "category": "lingerie-de-nuit",
      "price": 29.9,
      "images": [
        "/products/CJYD2478752/530a8963b8.webp",
        "/products/CJYD2478752/683300df55.webp",
        "/products/CJYD2478752/e1e353fb31.webp",
        "/products/CJYD2478752/81cab4b7ee.webp",
        "/products/CJYD2478752/a1012b7f3a.webp",
        "/products/CJYD2478752/bfd8d3998d.webp",
        "/products/CJYD2478752/ab8dfdbaf8.webp",
        "/products/CJYD2478752/0e987f48f6.webp",
        "/products/CJYD2478752/d77e983f4e.webp"
      ],
      "variants": [
        {
          "vid": "2509050112021608200",
          "sku": "CJYD247875201AZ",
          "key": "White-S",
          "color": "Blanc",
          "size": "S",
          "cost": 1.66,
          "image": "/products/CJYD2478752/0e987f48f6.webp"
        },
        {
          "vid": "2509050112021608400",
          "sku": "CJYD247875202BY",
          "key": "White-M",
          "color": "Blanc",
          "size": "M",
          "cost": 1.66,
          "image": "/products/CJYD2478752/0e987f48f6.webp"
        },
        {
          "vid": "2509050112021608500",
          "sku": "CJYD247875203CX",
          "key": "White-L",
          "color": "Blanc",
          "size": "L",
          "cost": 1.66,
          "image": "/products/CJYD2478752/0e987f48f6.webp"
        },
        {
          "vid": "2509050112021608600",
          "sku": "CJYD247875204DW",
          "key": "White-XL",
          "color": "Blanc",
          "size": "XL",
          "cost": 1.66,
          "image": "/products/CJYD2478752/0e987f48f6.webp"
        },
        {
          "vid": "2509050112021608800",
          "sku": "CJYD247875205EV",
          "key": "White-XXL",
          "color": "Blanc",
          "size": "XXL",
          "cost": 1.66,
          "image": "/products/CJYD2478752/0e987f48f6.webp"
        },
        {
          "vid": "2509050112031602000",
          "sku": "CJYD247875226ZA",
          "key": "Wine Red-S",
          "color": "Bordeaux",
          "size": "S",
          "cost": 1.66,
          "image": "/products/CJYD2478752/81cab4b7ee.webp"
        },
        {
          "vid": "2509050112031602100",
          "sku": "CJYD247875227AZ",
          "key": "Wine Red-M",
          "color": "Bordeaux",
          "size": "M",
          "cost": 1.66,
          "image": "/products/CJYD2478752/81cab4b7ee.webp"
        },
        {
          "vid": "2509050112031602300",
          "sku": "CJYD247875228BY",
          "key": "Wine Red-L",
          "color": "Bordeaux",
          "size": "L",
          "cost": 1.66,
          "image": "/products/CJYD2478752/81cab4b7ee.webp"
        },
        {
          "vid": "2509050112031602400",
          "sku": "CJYD247875229CX",
          "key": "Wine Red-XL",
          "color": "Bordeaux",
          "size": "XL",
          "cost": 1.66,
          "image": "/products/CJYD2478752/81cab4b7ee.webp"
        },
        {
          "vid": "2509050112031602600",
          "sku": "CJYD247875230DW",
          "key": "Wine Red-XXL",
          "color": "Bordeaux",
          "size": "XXL",
          "cost": 1.66,
          "image": "/products/CJYD2478752/81cab4b7ee.webp"
        },
        {
          "vid": "2509050112031601200",
          "sku": "CJYD247875221UF",
          "key": "Black-S",
          "color": "Noir",
          "size": "S",
          "cost": 1.66,
          "image": "/products/CJYD2478752/530a8963b8.webp"
        },
        {
          "vid": "2509050112031601300",
          "sku": "CJYD247875222VE",
          "key": "Black-M",
          "color": "Noir",
          "size": "M",
          "cost": 1.66,
          "image": "/products/CJYD2478752/530a8963b8.webp"
        },
        {
          "vid": "2509050112031601500",
          "sku": "CJYD247875223WD",
          "key": "Black-L",
          "color": "Noir",
          "size": "L",
          "cost": 1.66,
          "image": "/products/CJYD2478752/530a8963b8.webp"
        },
        {
          "vid": "2509050112031601600",
          "sku": "CJYD247875224XC",
          "key": "Black-XL",
          "color": "Noir",
          "size": "XL",
          "cost": 1.66,
          "image": "/products/CJYD2478752/530a8963b8.webp"
        },
        {
          "vid": "2509050112031601800",
          "sku": "CJYD247875225YB",
          "key": "Black-XXL",
          "color": "Noir",
          "size": "XXL",
          "cost": 1.66,
          "image": "/products/CJYD2478752/530a8963b8.webp"
        },
        {
          "vid": "2509050112021608900",
          "sku": "CJYD247875206FU",
          "key": "Red-S",
          "color": "Rouge",
          "size": "S",
          "cost": 1.66,
          "image": "/products/CJYD2478752/e1e353fb31.webp"
        },
        {
          "vid": "2509050112021609100",
          "sku": "CJYD247875207GT",
          "key": "Red-M",
          "color": "Rouge",
          "size": "M",
          "cost": 1.66,
          "image": "/products/CJYD2478752/e1e353fb31.webp"
        },
        {
          "vid": "2509050112021609200",
          "sku": "CJYD247875208HS",
          "key": "Red-L",
          "color": "Rouge",
          "size": "L",
          "cost": 1.66,
          "image": "/products/CJYD2478752/e1e353fb31.webp"
        },
        {
          "vid": "2509050112021609400",
          "sku": "CJYD247875209IR",
          "key": "Red-XL",
          "color": "Rouge",
          "size": "XL",
          "cost": 1.66,
          "image": "/products/CJYD2478752/e1e353fb31.webp"
        },
        {
          "vid": "2509050112021609500",
          "sku": "CJYD247875210JQ",
          "key": "Red-XXL",
          "color": "Rouge",
          "size": "XXL",
          "cost": 1.66,
          "image": "/products/CJYD2478752/e1e353fb31.webp"
        },
        {
          "vid": "2509050112021609700",
          "sku": "CJYD247875211KP",
          "key": "Purple-S",
          "color": "Violet",
          "size": "S",
          "cost": 1.66,
          "image": "/products/CJYD2478752/d77e983f4e.webp"
        },
        {
          "vid": "2509050112021609800",
          "sku": "CJYD247875212LO",
          "key": "Purple-M",
          "color": "Violet",
          "size": "M",
          "cost": 1.66,
          "image": "/products/CJYD2478752/d77e983f4e.webp"
        },
        {
          "vid": "2509050112031600000",
          "sku": "CJYD247875213MN",
          "key": "Purple-L",
          "color": "Violet",
          "size": "L",
          "cost": 1.66,
          "image": "/products/CJYD2478752/d77e983f4e.webp"
        },
        {
          "vid": "2509050112031600100",
          "sku": "CJYD247875214NM",
          "key": "Purple-XL",
          "color": "Violet",
          "size": "XL",
          "cost": 1.66,
          "image": "/products/CJYD2478752/d77e983f4e.webp"
        },
        {
          "vid": "2509050112031600300",
          "sku": "CJYD247875215OL",
          "key": "Purple-XXL",
          "color": "Violet",
          "size": "XXL",
          "cost": 1.66,
          "image": "/products/CJYD2478752/d77e983f4e.webp"
        }
      ],
      "isBestSeller": true
    },
    {
      "pid": "2608310224581636400",
      "sku": "CJYD3112546",
      "slug": "ensemble-porte-jarretelles-dentelle",
      "name": "Ensemble Porte-Jarretelles Dentelle",
      "cjName": "Lace Shapewear Sexy Lingerie Set",
      "description": "Soutien-gorge, porte-jarretelles et string en dentelle : un ensemble complet, pensé pour être porté avec des bas.",
      "category": "ensembles",
      "price": 44.9,
      "images": [
        "/products/CJYD3112546/e09dc033ff.webp",
        "/products/CJYD3112546/307faac340.webp",
        "/products/CJYD3112546/575c9fca7f.webp",
        "/products/CJYD3112546/be148976ce.webp",
        "/products/CJYD3112546/590cfbd4b5.webp",
        "/products/CJYD3112546/00d5fe0cfd.webp",
        "/products/CJYD3112546/4b793a07f5.webp",
        "/products/CJYD3112546/7e2047960f.webp"
      ],
      "defaultColor": "Noir et rouge",
      "variants": [
        {
          "vid": "2608310224581637315",
          "sku": "CJYD311254616PK",
          "key": "White-S",
          "color": "Blanc",
          "size": "S",
          "cost": 5.36,
          "image": "/products/CJYD3112546/575c9fca7f.webp"
        },
        {
          "vid": "2608310224581637316",
          "sku": "CJYD311254617QJ",
          "key": "White-M",
          "color": "Blanc",
          "size": "M",
          "cost": 5.36,
          "image": "/products/CJYD3112546/575c9fca7f.webp"
        },
        {
          "vid": "2608310224581637317",
          "sku": "CJYD311254618RI",
          "key": "White-L",
          "color": "Blanc",
          "size": "L",
          "cost": 5.36,
          "image": "/products/CJYD3112546/575c9fca7f.webp"
        },
        {
          "vid": "2608310224581637318",
          "sku": "CJYD311254619SH",
          "key": "White-XL",
          "color": "Blanc",
          "size": "XL",
          "cost": 5.36,
          "image": "/products/CJYD3112546/575c9fca7f.webp"
        },
        {
          "vid": "2608310224581637319",
          "sku": "CJYD311254620TG",
          "key": "White-XXL",
          "color": "Blanc",
          "size": "XXL",
          "cost": 5.36,
          "image": "/products/CJYD3112546/575c9fca7f.webp"
        },
        {
          "vid": "2608310224581637305",
          "sku": "CJYD311254606FU",
          "key": "Black Skin Color-S",
          "color": "Noir et nude",
          "size": "S",
          "cost": 5.36,
          "image": "/products/CJYD3112546/00d5fe0cfd.webp"
        },
        {
          "vid": "2608310224581637306",
          "sku": "CJYD311254607GT",
          "key": "Black Skin Color-M",
          "color": "Noir et nude",
          "size": "M",
          "cost": 5.36,
          "image": "/products/CJYD3112546/00d5fe0cfd.webp"
        },
        {
          "vid": "2608310224581637307",
          "sku": "CJYD311254608HS",
          "key": "Black Skin Color-L",
          "color": "Noir et nude",
          "size": "L",
          "cost": 5.36,
          "image": "/products/CJYD3112546/00d5fe0cfd.webp"
        },
        {
          "vid": "2608310224581637308",
          "sku": "CJYD311254609IR",
          "key": "Black Skin Color-XL",
          "color": "Noir et nude",
          "size": "XL",
          "cost": 5.36,
          "image": "/products/CJYD3112546/00d5fe0cfd.webp"
        },
        {
          "vid": "2608310224581637309",
          "sku": "CJYD311254610JQ",
          "key": "Black Skin Color-XXL",
          "color": "Noir et nude",
          "size": "XXL",
          "cost": 5.36,
          "image": "/products/CJYD3112546/00d5fe0cfd.webp"
        },
        {
          "vid": "2608310224581637300",
          "sku": "CJYD311254601AZ",
          "key": "Black And Red-S",
          "color": "Noir et rouge",
          "size": "S",
          "cost": 5.36,
          "image": "/products/CJYD3112546/590cfbd4b5.webp"
        },
        {
          "vid": "2608310224581637301",
          "sku": "CJYD311254602BY",
          "key": "Black And Red-M",
          "color": "Noir et rouge",
          "size": "M",
          "cost": 5.36,
          "image": "/products/CJYD3112546/590cfbd4b5.webp"
        },
        {
          "vid": "2608310224581637302",
          "sku": "CJYD311254603CX",
          "key": "Black And Red-L",
          "color": "Noir et rouge",
          "size": "L",
          "cost": 5.36,
          "image": "/products/CJYD3112546/590cfbd4b5.webp"
        },
        {
          "vid": "2608310224581637303",
          "sku": "CJYD311254604DW",
          "key": "Black And Red-XL",
          "color": "Noir et rouge",
          "size": "XL",
          "cost": 5.36,
          "image": "/products/CJYD3112546/590cfbd4b5.webp"
        },
        {
          "vid": "2608310224581637304",
          "sku": "CJYD311254605EV",
          "key": "Black And Red-XXL",
          "color": "Noir et rouge",
          "size": "XXL",
          "cost": 5.36,
          "image": "/products/CJYD3112546/590cfbd4b5.webp"
        },
        {
          "vid": "2608310224581637310",
          "sku": "CJYD311254611KP",
          "key": "Red-S",
          "color": "Rouge",
          "size": "S",
          "cost": 5.36,
          "image": "/products/CJYD3112546/7e2047960f.webp"
        },
        {
          "vid": "2608310224581637311",
          "sku": "CJYD311254612LO",
          "key": "Red-M",
          "color": "Rouge",
          "size": "M",
          "cost": 5.36,
          "image": "/products/CJYD3112546/7e2047960f.webp"
        },
        {
          "vid": "2608310224581637312",
          "sku": "CJYD311254613MN",
          "key": "Red-L",
          "color": "Rouge",
          "size": "L",
          "cost": 5.36,
          "image": "/products/CJYD3112546/7e2047960f.webp"
        },
        {
          "vid": "2608310224581637313",
          "sku": "CJYD311254614NM",
          "key": "Red-XL",
          "color": "Rouge",
          "size": "XL",
          "cost": 5.36,
          "image": "/products/CJYD3112546/7e2047960f.webp"
        },
        {
          "vid": "2608310224581637314",
          "sku": "CJYD311254615OL",
          "key": "Red-XXL",
          "color": "Rouge",
          "size": "XXL",
          "cost": 5.36,
          "image": "/products/CJYD3112546/7e2047960f.webp"
        }
      ],
      "isNew": true
    },
    {
      "pid": "2609141036461629600",
      "sku": "CJYD3162994",
      "slug": "ensemble-harnais",
      "name": "Ensemble Harnais",
      "cjName": "Women's Bonded Lingerie Strap Set",
      "description": "Soutien-gorge ouvert à harnais, string et jarretières. Des lignes nettes, un effet bijou sur la peau.",
      "category": "ensembles",
      "price": 29.9,
      "images": [
        "/products/CJYD3162994/90e8f2a840.webp",
        "/products/CJYD3162994/3e948bcb12.webp",
        "/products/CJYD3162994/22458375ba.webp",
        "/products/CJYD3162994/f282f9db4d.webp",
        "/products/CJYD3162994/4cd90af03e.webp",
        "/products/CJYD3162994/0f8f66ee62.webp"
      ],
      "variants": [
        {
          "vid": "2609141036471620500",
          "sku": "CJYD316299401AZ",
          "key": "Black-S",
          "color": "Noir",
          "size": "S",
          "cost": 2.62,
          "image": "/products/CJYD3162994/f282f9db4d.webp"
        },
        {
          "vid": "2609141036471620501",
          "sku": "CJYD316299402BY",
          "key": "Black-M",
          "color": "Noir",
          "size": "M",
          "cost": 2.62,
          "image": "/products/CJYD3162994/f282f9db4d.webp"
        },
        {
          "vid": "2609141036471620502",
          "sku": "CJYD316299403CX",
          "key": "Black-L",
          "color": "Noir",
          "size": "L",
          "cost": 2.62,
          "image": "/products/CJYD3162994/f282f9db4d.webp"
        },
        {
          "vid": "2609141036471620503",
          "sku": "CJYD316299404DW",
          "key": "Black-XL",
          "color": "Noir",
          "size": "XL",
          "cost": 2.62,
          "image": "/products/CJYD3162994/f282f9db4d.webp"
        },
        {
          "vid": "2609141036471620504",
          "sku": "CJYD316299405EV",
          "key": "Red-S",
          "color": "Rouge",
          "size": "S",
          "cost": 2.62,
          "image": "/products/CJYD3162994/3e948bcb12.webp"
        },
        {
          "vid": "2609141036471620505",
          "sku": "CJYD316299406FU",
          "key": "Red-M",
          "color": "Rouge",
          "size": "M",
          "cost": 2.62,
          "image": "/products/CJYD3162994/3e948bcb12.webp"
        },
        {
          "vid": "2609141036471620506",
          "sku": "CJYD316299407GT",
          "key": "Red-L",
          "color": "Rouge",
          "size": "L",
          "cost": 2.62,
          "image": "/products/CJYD3162994/3e948bcb12.webp"
        },
        {
          "vid": "2609141036471620507",
          "sku": "CJYD316299408HS",
          "key": "Red-XL",
          "color": "Rouge",
          "size": "XL",
          "cost": 2.62,
          "image": "/products/CJYD3162994/3e948bcb12.webp"
        }
      ]
    },
    {
      "pid": "2511160228431637400",
      "sku": "CJYD2593842",
      "slug": "ensemble-brode-balconnet",
      "name": "Ensemble Brodé Balconnet",
      "cjName": "Embroidery Sexy Lingerie Ladies Set",
      "description": "Balconnet brodé de motifs floraux et string assorti en tulle transparent. Un classique de la lingerie, tout en finesse.",
      "category": "ensembles",
      "price": 34.9,
      "images": [
        "/products/CJYD2593842/0adadd78ab.webp",
        "/products/CJYD2593842/82474c7f33.webp",
        "/products/CJYD2593842/3ab33a32fc.webp",
        "/products/CJYD2593842/5ce5d9bcf8.webp"
      ],
      "variants": [
        {
          "vid": "2511160228431638300",
          "sku": "CJYD259384205EV",
          "key": "White-S",
          "color": "Blanc",
          "size": "S",
          "cost": 3.15,
          "image": "/products/CJYD2593842/0adadd78ab.webp"
        },
        {
          "vid": "2511160228431638500",
          "sku": "CJYD259384206FU",
          "key": "White-M",
          "color": "Blanc",
          "size": "M",
          "cost": 3.15,
          "image": "/products/CJYD2593842/0adadd78ab.webp"
        },
        {
          "vid": "2511160228431638600",
          "sku": "CJYD259384207GT",
          "key": "White-L",
          "color": "Blanc",
          "size": "L",
          "cost": 3.15,
          "image": "/products/CJYD2593842/0adadd78ab.webp"
        },
        {
          "vid": "2511160228431638800",
          "sku": "CJYD259384208HS",
          "key": "White-XL",
          "color": "Blanc",
          "size": "XL",
          "cost": 3.15,
          "image": "/products/CJYD2593842/0adadd78ab.webp"
        },
        {
          "vid": "2511160228431639000",
          "sku": "CJYD259384209IR",
          "key": "Black-S",
          "color": "Noir",
          "size": "S",
          "cost": 3.15,
          "image": "/products/CJYD2593842/82474c7f33.webp"
        },
        {
          "vid": "2511160228431639200",
          "sku": "CJYD259384210JQ",
          "key": "Black-M",
          "color": "Noir",
          "size": "M",
          "cost": 3.15,
          "image": "/products/CJYD2593842/82474c7f33.webp"
        },
        {
          "vid": "2511160228431639300",
          "sku": "CJYD259384211KP",
          "key": "Black-L",
          "color": "Noir",
          "size": "L",
          "cost": 3.15,
          "image": "/products/CJYD2593842/82474c7f33.webp"
        },
        {
          "vid": "2511160228431639500",
          "sku": "CJYD259384212LO",
          "key": "Black-XL",
          "color": "Noir",
          "size": "XL",
          "cost": 3.15,
          "image": "/products/CJYD2593842/82474c7f33.webp"
        },
        {
          "vid": "2511160228441630300",
          "sku": "CJYD259384217QJ",
          "key": "Pink-S",
          "color": "Rose",
          "size": "S",
          "cost": 3.15,
          "image": "/products/CJYD2593842/5ce5d9bcf8.webp"
        },
        {
          "vid": "2511160228441630500",
          "sku": "CJYD259384218RI",
          "key": "Pink-M",
          "color": "Rose",
          "size": "M",
          "cost": 3.15,
          "image": "/products/CJYD2593842/5ce5d9bcf8.webp"
        },
        {
          "vid": "2511160228441630600",
          "sku": "CJYD259384219SH",
          "key": "Pink-L",
          "color": "Rose",
          "size": "L",
          "cost": 3.15,
          "image": "/products/CJYD2593842/5ce5d9bcf8.webp"
        },
        {
          "vid": "2511160228441630800",
          "sku": "CJYD259384220TG",
          "key": "Pink-XL",
          "color": "Rose",
          "size": "XL",
          "cost": 3.15,
          "image": "/products/CJYD2593842/5ce5d9bcf8.webp"
        },
        {
          "vid": "2511160228431637600",
          "sku": "CJYD259384201AZ",
          "key": "Red-S",
          "color": "Rouge",
          "size": "S",
          "cost": 3.15,
          "image": "/products/CJYD2593842/3ab33a32fc.webp"
        },
        {
          "vid": "2511160228431637800",
          "sku": "CJYD259384202BY",
          "key": "Red-M",
          "color": "Rouge",
          "size": "M",
          "cost": 3.15,
          "image": "/products/CJYD2593842/3ab33a32fc.webp"
        },
        {
          "vid": "2511160228431638000",
          "sku": "CJYD259384203CX",
          "key": "Red-L",
          "color": "Rouge",
          "size": "L",
          "cost": 3.15,
          "image": "/products/CJYD2593842/3ab33a32fc.webp"
        },
        {
          "vid": "2511160228431638200",
          "sku": "CJYD259384204DW",
          "key": "Red-XL",
          "color": "Rouge",
          "size": "XL",
          "cost": 3.15,
          "image": "/products/CJYD2593842/3ab33a32fc.webp"
        }
      ],
      "isBestSeller": true
    },
    {
      "pid": "1502912451724595200",
      "sku": "CJTZ1436797",
      "slug": "body-dentelle-dos-nu",
      "name": "Body Dentelle Dos Nu",
      "cjName": "Sexy Lingerie Lace Sheer Lingerie Open Back Bodysuit Lingerie",
      "description": "Body au décolleté en V bordé de cils de dentelle, dos nu et fines bretelles. Se porte seul ou sous une veste.",
      "category": "bodys",
      "price": 39.9,
      "images": [
        "/products/CJTZ1436797/3813d07117.webp",
        "/products/CJTZ1436797/63a169e4bc.webp",
        "/products/CJTZ1436797/b55037fd37.webp",
        "/products/CJTZ1436797/44998698c6.webp",
        "/products/CJTZ1436797/bbdf0783cf.webp",
        "/products/CJTZ1436797/faf93d275a.webp",
        "/products/CJTZ1436797/03b9e18e2a.webp",
        "/products/CJTZ1436797/07e45e5f55.webp",
        "/products/CJTZ1436797/0d0daf6fb9.webp",
        "/products/CJTZ1436797/df4d2b39f8.webp",
        "/products/CJTZ1436797/2c34b13bfb.webp",
        "/products/CJTZ1436797/0cda8bbfd0.webp",
        "/products/CJTZ1436797/b6df51387b.webp",
        "/products/CJTZ1436797/b48c2c53e5.webp"
      ],
      "variants": [
        {
          "vid": "1502912451745566721",
          "sku": "CJTZ1436797-White-S",
          "key": "White-S",
          "color": "Blanc",
          "size": "S",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/44998698c6.webp"
        },
        {
          "vid": "1502912451745566726",
          "sku": "CJTZ1436797-White-M",
          "key": "White-M",
          "color": "Blanc",
          "size": "M",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/44998698c6.webp"
        },
        {
          "vid": "1502912451745566731",
          "sku": "CJTZ1436797-White-L",
          "key": "White-L",
          "color": "Blanc",
          "size": "L",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/44998698c6.webp"
        },
        {
          "vid": "1502912451745566736",
          "sku": "CJTZ1436797-White-XL",
          "key": "White-XL",
          "color": "Blanc",
          "size": "XL",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/44998698c6.webp"
        },
        {
          "vid": "1502912451745566741",
          "sku": "CJTZ1436797-White-XXL",
          "key": "White-XXL",
          "color": "Blanc",
          "size": "XXL",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/44998698c6.webp"
        },
        {
          "vid": "1502912451745566724",
          "sku": "CJTZ1436797-Leopard print-S",
          "key": "Leopard print-S",
          "color": "Léopard",
          "size": "S",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/63a169e4bc.webp"
        },
        {
          "vid": "1502912451745566729",
          "sku": "CJTZ1436797-Leopard print-M",
          "key": "Leopard print-M",
          "color": "Léopard",
          "size": "M",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/63a169e4bc.webp"
        },
        {
          "vid": "1502912451745566734",
          "sku": "CJTZ1436797-Leopard print-L",
          "key": "Leopard print-L",
          "color": "Léopard",
          "size": "L",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/63a169e4bc.webp"
        },
        {
          "vid": "1502912451745566739",
          "sku": "CJTZ1436797-Leopard print-XL",
          "key": "Leopard print-XL",
          "color": "Léopard",
          "size": "XL",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/63a169e4bc.webp"
        },
        {
          "vid": "1502912451745566744",
          "sku": "CJTZ1436797-Leopard print-XXL",
          "key": "Leopard print-XXL",
          "color": "Léopard",
          "size": "XXL",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/63a169e4bc.webp"
        },
        {
          "vid": "1502912451745566720",
          "sku": "CJTZ1436797-Black-S",
          "key": "Black-S",
          "color": "Noir",
          "size": "S",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/3813d07117.webp"
        },
        {
          "vid": "1502912451745566725",
          "sku": "CJTZ1436797-Black-M",
          "key": "Black-M",
          "color": "Noir",
          "size": "M",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/3813d07117.webp"
        },
        {
          "vid": "1502912451745566730",
          "sku": "CJTZ1436797-Black-L",
          "key": "Black-L",
          "color": "Noir",
          "size": "L",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/3813d07117.webp"
        },
        {
          "vid": "1502912451745566735",
          "sku": "CJTZ1436797-Black-XL",
          "key": "Black-XL",
          "color": "Noir",
          "size": "XL",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/3813d07117.webp"
        },
        {
          "vid": "1502912451745566740",
          "sku": "CJTZ1436797-Black-XXL",
          "key": "Black-XXL",
          "color": "Noir",
          "size": "XXL",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/3813d07117.webp"
        },
        {
          "vid": "1502912451745566722",
          "sku": "CJTZ1436797-Red-S",
          "key": "Red-S",
          "color": "Rouge",
          "size": "S",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/b6df51387b.webp"
        },
        {
          "vid": "1502912451745566727",
          "sku": "CJTZ1436797-Red-M",
          "key": "Red-M",
          "color": "Rouge",
          "size": "M",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/b6df51387b.webp"
        },
        {
          "vid": "1502912451745566732",
          "sku": "CJTZ1436797-Red-L",
          "key": "Red-L",
          "color": "Rouge",
          "size": "L",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/b6df51387b.webp"
        },
        {
          "vid": "1502912451745566737",
          "sku": "CJTZ1436797-Red-XL",
          "key": "Red-XL",
          "color": "Rouge",
          "size": "XL",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/b6df51387b.webp"
        },
        {
          "vid": "1502912451745566742",
          "sku": "CJTZ1436797-Red-XXL",
          "key": "Red-XXL",
          "color": "Rouge",
          "size": "XXL",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/b6df51387b.webp"
        },
        {
          "vid": "1557906496699650048",
          "sku": "CJTZ1436797-Purple-S",
          "key": "Purple-S",
          "color": "Violet",
          "size": "S",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/b48c2c53e5.webp"
        },
        {
          "vid": "1557906496699650049",
          "sku": "CJTZ1436797-Purple-M",
          "key": "Purple-M",
          "color": "Violet",
          "size": "M",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/b48c2c53e5.webp"
        },
        {
          "vid": "1557906496699650050",
          "sku": "CJTZ1436797-Purple-L",
          "key": "Purple-L",
          "color": "Violet",
          "size": "L",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/b48c2c53e5.webp"
        },
        {
          "vid": "1557906496699650051",
          "sku": "CJTZ1436797-Purple-XL",
          "key": "Purple-XL",
          "color": "Violet",
          "size": "XL",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/b48c2c53e5.webp"
        },
        {
          "vid": "1557906496699650052",
          "sku": "CJTZ1436797-Purple-XXL",
          "key": "Purple-XXL",
          "color": "Violet",
          "size": "XXL",
          "cost": 5.31,
          "image": "/products/CJTZ1436797/b48c2c53e5.webp"
        }
      ],
      "isNew": true
    },
    {
      "pid": "2511150722431632300",
      "sku": "CJYD2593351",
      "slug": "ensemble-plumetis",
      "name": "Ensemble Plumetis",
      "cjName": "Sexy Lingerie French Bra Ultra-thin Mesh Lingerie Set",
      "description": "Soutien-gorge et string en tulle plumetis ultra-fin. Une transparence délicate, presque invisible sous les vêtements.",
      "category": "ensembles",
      "price": 32.9,
      "images": [
        "/products/CJYD2593351/9188623df7.webp",
        "/products/CJYD2593351/61d5d96852.webp",
        "/products/CJYD2593351/2e48324d7e.webp",
        "/products/CJYD2593351/7d804ea9eb.webp",
        "/products/CJYD2593351/73fb669629.webp"
      ],
      "variants": [
        {
          "vid": "2511150722431632500",
          "sku": "CJYD259335101AZ",
          "key": "Leopard Print-S",
          "color": "Noir",
          "size": "S",
          "cost": 4.18,
          "image": "/products/CJYD2593351/73fb669629.webp"
        },
        {
          "vid": "2511150722431632600",
          "sku": "CJYD259335102BY",
          "key": "Leopard Print-M",
          "color": "Noir",
          "size": "M",
          "cost": 4.18,
          "image": "/products/CJYD2593351/73fb669629.webp"
        },
        {
          "vid": "2511150722431632800",
          "sku": "CJYD259335103CX",
          "key": "Leopard Print-L",
          "color": "Noir",
          "size": "L",
          "cost": 4.18,
          "image": "/products/CJYD2593351/73fb669629.webp"
        }
      ]
    },
    {
      "pid": "00EFAD6C-3E2E-4973-983C-198B98CE0927",
      "sku": "CJNSSYTZ03935",
      "slug": "bralette-shorty-dentelle",
      "name": "Bralette & Shorty Dentelle",
      "cjName": "Sexy lingerie bra",
      "description": "Bralette sans armatures et shorty en dentelle, bretelles croisées dans le dos. Taille unique, tout en douceur.",
      "category": "ensembles",
      "price": 29.9,
      "images": [
        "/products/CJNSSYTZ03935/ab65a3616f.webp"
      ],
      "variants": [
        {
          "vid": "6C8EBA53-9EC9-4A1D-AA3B-1CAD84F4C5EF",
          "sku": "CJNSSYTZ03935-White",
          "key": "White",
          "color": "Blanc",
          "size": "UNIQUE",
          "cost": 5.22,
          "image": "/products/CJNSSYTZ03935/14da59c157.webp"
        },
        {
          "vid": "B778F9AE-6377-4C14-BAFE-ADFD7838CEA9",
          "sku": "CJNSSYTZ03935-Black",
          "key": "Black",
          "color": "Noir",
          "size": "UNIQUE",
          "cost": 5.22,
          "image": "/products/CJNSSYTZ03935/9db188cc07.webp"
        },
        {
          "vid": "97981D0C-536A-438D-A311-12194E23122F",
          "sku": "CJNSSYTZ03935-Pink",
          "key": "Pink",
          "color": "Rose poudré",
          "size": "UNIQUE",
          "cost": 5.22,
          "image": "/products/CJNSSYTZ03935/ab65a3616f.webp"
        },
        {
          "vid": "50EC80DA-5F86-4440-B84E-5126B9B9E1B0",
          "sku": "CJNSSYTZ03935-Red",
          "key": "Red",
          "color": "Rouge",
          "size": "UNIQUE",
          "cost": 5.22,
          "image": "/products/CJNSSYTZ03935/4a4f796aaf.webp"
        }
      ]
    },
    {
      "pid": "1493492942826807297",
      "sku": "CJQQ1416310",
      "slug": "body-dentelle-ajoure",
      "name": "Body Dentelle Ajouré",
      "cjName": "Lace Lingerie Bodysuit One-piece Lingerie Set Black Lingerie",
      "description": "Body en dentelle noire aux découpes ajourées sur la taille, décolleté plongeant bordé de cils.",
      "category": "bodys",
      "price": 34.9,
      "images": [
        "/products/CJQQ1416310/6e0da0db3e.webp",
        "/products/CJQQ1416310/9bd0abc73c.webp",
        "/products/CJQQ1416310/c01caae8bc.webp",
        "/products/CJQQ1416310/949058af85.webp",
        "/products/CJQQ1416310/55596bbce1.webp",
        "/products/CJQQ1416310/669fb81a31.webp"
      ],
      "variants": [
        {
          "vid": "1493492942856167425",
          "sku": "CJQQ1416310-Black-S",
          "key": "Black-S",
          "color": "Noir",
          "size": "S",
          "cost": 3.87,
          "image": "/products/CJQQ1416310/6e0da0db3e.webp"
        },
        {
          "vid": "1493492942856167426",
          "sku": "CJQQ1416310-Black-M",
          "key": "Black-M",
          "color": "Noir",
          "size": "M",
          "cost": 3.87,
          "image": "/products/CJQQ1416310/6e0da0db3e.webp"
        },
        {
          "vid": "1493492942856167427",
          "sku": "CJQQ1416310-Black-L",
          "key": "Black-L",
          "color": "Noir",
          "size": "L",
          "cost": 3.87,
          "image": "/products/CJQQ1416310/6e0da0db3e.webp"
        }
      ]
    },
    {
      "pid": "1403890646363803648",
      "sku": "CJSY1172234",
      "slug": "body-resille",
      "name": "Body Résille",
      "cjName": "New Sexy Lingerie Women Teddies Bodysuit Erotic Lingerie Crotch Stretch",
      "description": "Body extensible en résille et dentelle, en trois coupes : manches longues, dos croisé ou col licou. Taille unique.",
      "category": "bodys",
      "price": 24.9,
      "images": [
        "/products/CJSY1172234/6199716f8c.webp",
        "/products/CJSY1172234/666bb22c88.webp",
        "/products/CJSY1172234/ab078d0850.webp",
        "/products/CJSY1172234/adb7d2469e.webp",
        "/products/CJSY1172234/bac62aed8e.webp",
        "/products/CJSY1172234/49485bac75.webp"
      ],
      "variants": [
        {
          "vid": "1403890647810838528",
          "sku": "CJSY117223403CX",
          "key": "Black AA-One size",
          "color": "Noir col licou",
          "size": "Unique",
          "cost": 1.74,
          "image": "/products/CJSY1172234/adb7d2469e.webp"
        },
        {
          "vid": "1403890647798255616",
          "sku": "CJSY117223402BY",
          "key": "Black A-One size",
          "color": "Noir croisé",
          "size": "Unique",
          "cost": 1.73,
          "image": "/products/CJSY1172234/49485bac75.webp"
        },
        {
          "vid": "1403890647773089792",
          "sku": "CJSY117223401AZ",
          "key": "Black-One size",
          "color": "Noir manches longues",
          "size": "Unique",
          "cost": 1.96,
          "image": "/products/CJSY1172234/6199716f8c.webp"
        }
      ]
    },
    {
      "pid": "2510020117091659600",
      "sku": "CJYD2547399",
      "slug": "ensemble-satin-a-lanieres",
      "name": "Ensemble Satin à Lanières",
      "cjName": "Lingerie Set For Women Strappy Lingerie Underwire Push Up",
      "description": "Soutien-gorge push-up à armatures, culotte et lanières en satin brillant qui dessinent la silhouette.",
      "category": "ensembles",
      "price": 59.9,
      "images": [
        "/products/CJYD2547399/f2cc17b74a.webp",
        "/products/CJYD2547399/8400843248.webp",
        "/products/CJYD2547399/0744c27c1a.webp",
        "/products/CJYD2547399/f0796b1c0d.webp",
        "/products/CJYD2547399/ce18f4e5ae.webp",
        "/products/CJYD2547399/8090aacf66.webp",
        "/products/CJYD2547399/24df913666.webp"
      ],
      "defaultColor": "Rose poudré",
      "variants": [
        {
          "vid": "2510020117101655300",
          "sku": "CJYD254739936JQ",
          "key": "White-S",
          "color": "Blanc",
          "size": "S",
          "cost": 14.68,
          "image": "/products/CJYD2547399/24df913666.webp"
        },
        {
          "vid": "2510020117101655400",
          "sku": "CJYD254739937KP",
          "key": "White-M",
          "color": "Blanc",
          "size": "M",
          "cost": 14.68,
          "image": "/products/CJYD2547399/24df913666.webp"
        },
        {
          "vid": "2510020117101655600",
          "sku": "CJYD254739938LO",
          "key": "White-L",
          "color": "Blanc",
          "size": "L",
          "cost": 14.68,
          "image": "/products/CJYD2547399/24df913666.webp"
        },
        {
          "vid": "2510020117101655700",
          "sku": "CJYD254739939MN",
          "key": "White-XL",
          "color": "Blanc",
          "size": "XL",
          "cost": 14.68,
          "image": "/products/CJYD2547399/24df913666.webp"
        },
        {
          "vid": "2510020117101655900",
          "sku": "CJYD254739940NM",
          "key": "White-2XL",
          "color": "Blanc",
          "size": "2XL",
          "cost": 14.68,
          "image": "/products/CJYD2547399/24df913666.webp"
        },
        {
          "vid": "2510020117101653000",
          "sku": "CJYD254739921UF",
          "key": "Burgundy-S",
          "color": "Bordeaux",
          "size": "S",
          "cost": 14.68,
          "image": "/products/CJYD2547399/8090aacf66.webp"
        },
        {
          "vid": "2510020117101653200",
          "sku": "CJYD254739922VE",
          "key": "Burgundy-M",
          "color": "Bordeaux",
          "size": "M",
          "cost": 14.68,
          "image": "/products/CJYD2547399/8090aacf66.webp"
        },
        {
          "vid": "2510020117101653300",
          "sku": "CJYD254739923WD",
          "key": "Burgundy-L",
          "color": "Bordeaux",
          "size": "L",
          "cost": 14.68,
          "image": "/products/CJYD2547399/8090aacf66.webp"
        },
        {
          "vid": "2510020117101653500",
          "sku": "CJYD254739924XC",
          "key": "Burgundy-XL",
          "color": "Bordeaux",
          "size": "XL",
          "cost": 14.68,
          "image": "/products/CJYD2547399/8090aacf66.webp"
        },
        {
          "vid": "2510020117101653600",
          "sku": "CJYD254739925YB",
          "key": "Burgundy-2XL",
          "color": "Bordeaux",
          "size": "2XL",
          "cost": 14.68,
          "image": "/products/CJYD2547399/8090aacf66.webp"
        },
        {
          "vid": "2510020117101650600",
          "sku": "CJYD254739906FU",
          "key": "Black-S",
          "color": "Noir",
          "size": "S",
          "cost": 14.68,
          "image": "/products/CJYD2547399/0744c27c1a.webp"
        },
        {
          "vid": "2510020117101650700",
          "sku": "CJYD254739907GT",
          "key": "Black-M",
          "color": "Noir",
          "size": "M",
          "cost": 14.68,
          "image": "/products/CJYD2547399/0744c27c1a.webp"
        },
        {
          "vid": "2510020117101650900",
          "sku": "CJYD254739908HS",
          "key": "Black-L",
          "color": "Noir",
          "size": "L",
          "cost": 14.68,
          "image": "/products/CJYD2547399/0744c27c1a.webp"
        },
        {
          "vid": "2510020117101651000",
          "sku": "CJYD254739909IR",
          "key": "Black-XL",
          "color": "Noir",
          "size": "XL",
          "cost": 14.68,
          "image": "/products/CJYD2547399/0744c27c1a.webp"
        },
        {
          "vid": "2510020117101651400",
          "sku": "CJYD254739910JQ",
          "key": "Black-2XL",
          "color": "Noir",
          "size": "2XL",
          "cost": 14.68,
          "image": "/products/CJYD2547399/0744c27c1a.webp"
        },
        {
          "vid": "2510020117091659800",
          "sku": "CJYD254739901AZ",
          "key": "Pink-S",
          "color": "Rose poudré",
          "size": "S",
          "cost": 14.68,
          "image": "/products/CJYD2547399/8400843248.webp"
        },
        {
          "vid": "2510020117091659900",
          "sku": "CJYD254739902BY",
          "key": "Pink-M",
          "color": "Rose poudré",
          "size": "M",
          "cost": 14.68,
          "image": "/products/CJYD2547399/8400843248.webp"
        },
        {
          "vid": "2510020117101650100",
          "sku": "CJYD254739903CX",
          "key": "Pink-L",
          "color": "Rose poudré",
          "size": "L",
          "cost": 14.68,
          "image": "/products/CJYD2547399/8400843248.webp"
        },
        {
          "vid": "2510020117101650300",
          "sku": "CJYD254739904DW",
          "key": "Pink-XL",
          "color": "Rose poudré",
          "size": "XL",
          "cost": 14.68,
          "image": "/products/CJYD2547399/8400843248.webp"
        },
        {
          "vid": "2510020117101650400",
          "sku": "CJYD254739905EV",
          "key": "Pink-2XL",
          "color": "Rose poudré",
          "size": "2XL",
          "cost": 14.68,
          "image": "/products/CJYD2547399/8400843248.webp"
        },
        {
          "vid": "2510020117101652300",
          "sku": "CJYD254739916PK",
          "key": "Purple-S",
          "color": "Violet",
          "size": "S",
          "cost": 14.68,
          "image": "/products/CJYD2547399/f0796b1c0d.webp"
        },
        {
          "vid": "2510020117101652400",
          "sku": "CJYD254739917QJ",
          "key": "Purple-M",
          "color": "Violet",
          "size": "M",
          "cost": 14.68,
          "image": "/products/CJYD2547399/f0796b1c0d.webp"
        },
        {
          "vid": "2510020117101652600",
          "sku": "CJYD254739918RI",
          "key": "Purple-L",
          "color": "Violet",
          "size": "L",
          "cost": 14.68,
          "image": "/products/CJYD2547399/f0796b1c0d.webp"
        },
        {
          "vid": "2510020117101652700",
          "sku": "CJYD254739919SH",
          "key": "Purple-XL",
          "color": "Violet",
          "size": "XL",
          "cost": 14.68,
          "image": "/products/CJYD2547399/f0796b1c0d.webp"
        },
        {
          "vid": "2510020117101652900",
          "sku": "CJYD254739920TG",
          "key": "Purple-2XL",
          "color": "Violet",
          "size": "2XL",
          "cost": 14.68,
          "image": "/products/CJYD2547399/f0796b1c0d.webp"
        }
      ],
      "isNew": true
    },
    {
      "pid": "2603110917401639000",
      "sku": "CJYD2783884",
      "slug": "ensemble-dentelle-genereuse",
      "name": "Ensemble Dentelle Généreuse",
      "cjName": "Lingerie Set Womens Lingerie For Large Bust",
      "description": "Soutien-gorge corbeille à armatures et string en dentelle, pensés pour les poitrines généreuses.",
      "category": "ensembles",
      "price": 34.9,
      "images": [
        "/products/CJYD2783884/6b0c976200.webp",
        "/products/CJYD2783884/827c429c21.webp",
        "/products/CJYD2783884/662b95caa3.webp"
      ],
      "variants": [
        {
          "vid": "2603110917411630800",
          "sku": "CJYD278388405EV",
          "key": "Purple-S",
          "color": "Lilas",
          "size": "S",
          "cost": 4.51,
          "image": "/products/CJYD2783884/6b0c976200.webp"
        },
        {
          "vid": "2603110917411631100",
          "sku": "CJYD278388406FU",
          "key": "Purple-M",
          "color": "Lilas",
          "size": "M",
          "cost": 4.51,
          "image": "/products/CJYD2783884/6b0c976200.webp"
        },
        {
          "vid": "2603110917411631500",
          "sku": "CJYD278388407GT",
          "key": "Purple-L",
          "color": "Lilas",
          "size": "L",
          "cost": 4.51,
          "image": "/products/CJYD2783884/6b0c976200.webp"
        },
        {
          "vid": "2603110917411631900",
          "sku": "CJYD278388408HS",
          "key": "Purple-XL",
          "color": "Lilas",
          "size": "XL",
          "cost": 4.51,
          "image": "/products/CJYD2783884/6b0c976200.webp"
        }
      ]
    },
    {
      "pid": "2511290304101614400",
      "sku": "CJYD2624815",
      "slug": "deguisement-policiere",
      "name": "Déguisement Policière",
      "cjName": "Sexy Lingerie Set Passionate Temptation Uniform",
      "description": "Body zippé en tulle bleu marine orné d'un écusson, porte-jarretelles et string assortis. Avec ou sans casquette, pour des jeux de rôle en toute élégance.",
      "category": "ensembles",
      "price": 44.9,
      "images": [
        "/products/CJYD2624815/7224586002.webp",
        "/products/CJYD2624815/145a7bba4c.webp",
        "/products/CJYD2624815/d1d5759a02.webp",
        "/products/CJYD2624815/3204624b79.webp",
        "/products/CJYD2624815/ad10ef6f3c.webp",
        "/products/CJYD2624815/670040d227.webp",
        "/products/CJYD2624815/96b6026d02.webp"
      ],
      "defaultColor": "Bleu marine avec casquette",
      "variants": [
        {
          "vid": "2511290304101614600",
          "sku": "CJYD262481501AZ",
          "key": "Navy Blue-S",
          "color": "Bleu marine avec casquette",
          "size": "S",
          "cost": 6.3,
          "image": "/products/CJYD2624815/7224586002.webp"
        },
        {
          "vid": "2511290304101614800",
          "sku": "CJYD262481502BY",
          "key": "Navy Blue-M",
          "color": "Bleu marine avec casquette",
          "size": "M",
          "cost": 6.3,
          "image": "/products/CJYD2624815/7224586002.webp"
        },
        {
          "vid": "2511290304101614900",
          "sku": "CJYD262481503CX",
          "key": "Navy Blue-L",
          "color": "Bleu marine avec casquette",
          "size": "L",
          "cost": 6.3,
          "image": "/products/CJYD2624815/7224586002.webp"
        },
        {
          "vid": "2511290304101615100",
          "sku": "CJYD262481504DW",
          "key": "Navy Blue-XL",
          "color": "Bleu marine avec casquette",
          "size": "XL",
          "cost": 6.3,
          "image": "/products/CJYD2624815/7224586002.webp"
        },
        {
          "vid": "2511290304101615300",
          "sku": "CJYD262481505EV",
          "key": "Navy Blue Without Hat-S",
          "color": "Bleu marine sans casquette",
          "size": "S",
          "cost": 5.47,
          "image": "/products/CJYD2624815/96b6026d02.webp"
        },
        {
          "vid": "2511290304101615400",
          "sku": "CJYD262481506FU",
          "key": "Navy Blue Without Hat-M",
          "color": "Bleu marine sans casquette",
          "size": "M",
          "cost": 5.47,
          "image": "/products/CJYD2624815/96b6026d02.webp"
        },
        {
          "vid": "2511290304101615600",
          "sku": "CJYD262481507GT",
          "key": "Navy Blue Without Hat-L",
          "color": "Bleu marine sans casquette",
          "size": "L",
          "cost": 5.47,
          "image": "/products/CJYD2624815/96b6026d02.webp"
        },
        {
          "vid": "2511290304101615800",
          "sku": "CJYD262481508HS",
          "key": "Navy Blue Without Hat-XL",
          "color": "Bleu marine sans casquette",
          "size": "XL",
          "cost": 5.47,
          "image": "/products/CJYD2624815/96b6026d02.webp"
        }
      ]
    },
    {
      "pid": "1493522176563662850",
      "sku": "CJQQ1416474",
      "slug": "deguisement-ecoliere",
      "name": "Déguisement Écolière",
      "cjName": "Sexy Lingerie Uniform Style Lingerie",
      "description": "Haut dos nu à col et cravate, jupe plissée à carreaux bordée de dentelle et string assorti. Six tartans au choix.",
      "category": "ensembles",
      "price": 34.9,
      "images": [
        "/products/CJQQ1416474/4fd91a551a.webp",
        "/products/CJQQ1416474/d6de785fc0.webp",
        "/products/CJQQ1416474/fca6e06b0e.webp",
        "/products/CJQQ1416474/96fa1b67f0.webp",
        "/products/CJQQ1416474/5a9fbc24ee.webp",
        "/products/CJQQ1416474/44c7f5982b.webp"
      ],
      "defaultColor": "Carreaux violets",
      "variants": [
        {
          "vid": "1502817193196146693",
          "sku": "CJQQ1416474-Grey-S",
          "key": "Grey-S",
          "color": "Carreaux gris",
          "size": "S",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/fca6e06b0e.webp"
        },
        {
          "vid": "1502817193196146700",
          "sku": "CJQQ1416474-Grey-M",
          "key": "Grey-M",
          "color": "Carreaux gris",
          "size": "M",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/fca6e06b0e.webp"
        },
        {
          "vid": "1502817193196146707",
          "sku": "CJQQ1416474-Grey-L",
          "key": "Grey-L",
          "color": "Carreaux gris",
          "size": "L",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/fca6e06b0e.webp"
        },
        {
          "vid": "1502817193196146714",
          "sku": "CJQQ1416474-Grey-XL",
          "key": "Grey-XL",
          "color": "Carreaux gris",
          "size": "XL",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/fca6e06b0e.webp"
        },
        {
          "vid": "1502817193196146721",
          "sku": "CJQQ1416474-Grey-XXL",
          "key": "Grey-XXL",
          "color": "Carreaux gris",
          "size": "XXL",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/fca6e06b0e.webp"
        },
        {
          "vid": "1502817193196146688",
          "sku": "CJQQ1416474-Yellow-S",
          "key": "Yellow-S",
          "color": "Carreaux jaunes",
          "size": "S",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/44c7f5982b.webp"
        },
        {
          "vid": "1502817193196146695",
          "sku": "CJQQ1416474-Yellow-M",
          "key": "Yellow-M",
          "color": "Carreaux jaunes",
          "size": "M",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/44c7f5982b.webp"
        },
        {
          "vid": "1502817193196146702",
          "sku": "CJQQ1416474-Yellow-L",
          "key": "Yellow-L",
          "color": "Carreaux jaunes",
          "size": "L",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/44c7f5982b.webp"
        },
        {
          "vid": "1502817193196146709",
          "sku": "CJQQ1416474-Yellow-XL",
          "key": "Yellow-XL",
          "color": "Carreaux jaunes",
          "size": "XL",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/44c7f5982b.webp"
        },
        {
          "vid": "1502817193196146716",
          "sku": "CJQQ1416474-Yellow-XXL",
          "key": "Yellow-XXL",
          "color": "Carreaux jaunes",
          "size": "XXL",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/44c7f5982b.webp"
        },
        {
          "vid": "1502817193196146692",
          "sku": "CJQQ1416474-Pink-S",
          "key": "Pink-S",
          "color": "Carreaux roses",
          "size": "S",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/96fa1b67f0.webp"
        },
        {
          "vid": "1502817193196146706",
          "sku": "CJQQ1416474-Pink-L",
          "key": "Pink-L",
          "color": "Carreaux roses",
          "size": "L",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/96fa1b67f0.webp"
        },
        {
          "vid": "1502817193196146690",
          "sku": "CJQQ1416474-Black-S",
          "key": "Black-S",
          "color": "Carreaux rouges, haut noir",
          "size": "S",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/5a9fbc24ee.webp"
        },
        {
          "vid": "1502817193196146697",
          "sku": "CJQQ1416474-Black-M",
          "key": "Black-M",
          "color": "Carreaux rouges, haut noir",
          "size": "M",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/5a9fbc24ee.webp"
        },
        {
          "vid": "1502817193196146704",
          "sku": "CJQQ1416474-Black-L",
          "key": "Black-L",
          "color": "Carreaux rouges, haut noir",
          "size": "L",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/5a9fbc24ee.webp"
        },
        {
          "vid": "1502817193196146711",
          "sku": "CJQQ1416474-Black-XL",
          "key": "Black-XL",
          "color": "Carreaux rouges, haut noir",
          "size": "XL",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/5a9fbc24ee.webp"
        },
        {
          "vid": "1502817193196146718",
          "sku": "CJQQ1416474-Black-XXL",
          "key": "Black-XXL",
          "color": "Carreaux rouges, haut noir",
          "size": "XXL",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/5a9fbc24ee.webp"
        },
        {
          "vid": "1502817193196146694",
          "sku": "CJQQ1416474-Dark Green-S",
          "key": "Dark Green-S",
          "color": "Carreaux verts",
          "size": "S",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/d6de785fc0.webp"
        },
        {
          "vid": "1502817193196146701",
          "sku": "CJQQ1416474-Dark Green-M",
          "key": "Dark Green-M",
          "color": "Carreaux verts",
          "size": "M",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/d6de785fc0.webp"
        },
        {
          "vid": "1502817193196146708",
          "sku": "CJQQ1416474-Dark Green-L",
          "key": "Dark Green-L",
          "color": "Carreaux verts",
          "size": "L",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/d6de785fc0.webp"
        },
        {
          "vid": "1502817193196146715",
          "sku": "CJQQ1416474-Dark Green-XL",
          "key": "Dark Green-XL",
          "color": "Carreaux verts",
          "size": "XL",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/d6de785fc0.webp"
        },
        {
          "vid": "1502817193196146722",
          "sku": "CJQQ1416474-Dark Green-XXL",
          "key": "Dark Green-XXL",
          "color": "Carreaux verts",
          "size": "XXL",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/d6de785fc0.webp"
        },
        {
          "vid": "1502817193196146689",
          "sku": "CJQQ1416474-Purple-S",
          "key": "Purple-S",
          "color": "Carreaux violets",
          "size": "S",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/4fd91a551a.webp"
        },
        {
          "vid": "1502817193196146696",
          "sku": "CJQQ1416474-Purple-M",
          "key": "Purple-M",
          "color": "Carreaux violets",
          "size": "M",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/4fd91a551a.webp"
        },
        {
          "vid": "1502817193196146703",
          "sku": "CJQQ1416474-Purple-L",
          "key": "Purple-L",
          "color": "Carreaux violets",
          "size": "L",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/4fd91a551a.webp"
        },
        {
          "vid": "1502817193196146710",
          "sku": "CJQQ1416474-Purple-XL",
          "key": "Purple-XL",
          "color": "Carreaux violets",
          "size": "XL",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/4fd91a551a.webp"
        },
        {
          "vid": "1502817193196146717",
          "sku": "CJQQ1416474-Purple-XXL",
          "key": "Purple-XXL",
          "color": "Carreaux violets",
          "size": "XXL",
          "cost": 4.86,
          "image": "/products/CJQQ1416474/4fd91a551a.webp"
        }
      ]
    }
  ]
}
