/** Shape of the catalogue generated by `npm run cj:import` (see cj/README.md). */

export type CjCatalogVariant = {
  /** CJ variant id - the key used for stock and orders */
  vid: string
  sku: string
  /** CJ variant key, e.g. "Black-M" */
  key: string
  color: string
  size: string
  /** CJ purchase price, USD */
  cost: number
  image?: string
}

export type CjCatalogProduct = {
  pid: string
  sku: string
  slug: string
  name: string
  /** original CJ title, for reference */
  cjName: string
  description?: string
  /** one of the category slugs of catalog.ts */
  category: string
  /** selling price, EUR */
  price: number
  images: string[]
  variants: CjCatalogVariant[]
  isNew?: boolean
  isBestSeller?: boolean
}

export type CjCatalog = {
  generatedAt: string | null
  mock?: boolean
  products: CjCatalogProduct[]
}
